# Generated by Django 4.2.6 on 2025-07-26 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=300)),
                ("checksum", models.CharField(max_length=32)),
                ("size", models.BigIntegerField()),
                ("file_path", models.CharField(max_length=500)),
                ("thumbnail_small", models.CharField(blank=True, max_length=100)),
                ("thumbnail_medium", models.CharField(blank=True, max_length=100)),
                ("thumbnail_large", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(default="active", max_length=20)),
                ("imaging_diagnostic", models.CharField(max_length=50)),
                ("tags", models.JSONField(default=list)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                ("short_title", models.CharField(blank=True, max_length=100)),
                ("acronym", models.CharField(blank=True, max_length=20)),
                ("introduction", models.TextField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("small_logo_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Institution",
                "verbose_name_plural": "Institutions",
            },
        ),
        migrations.CreateModel(
            name="Locale",
            fields=[
                (
                    "key",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
            ],
            options={
                "verbose_name": "Locale",
                "verbose_name_plural": "Locales",
            },
        ),
        migrations.CreateModel(
            name="OrganSystem",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Organ System",
                "verbose_name_plural": "Organ Systems",
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Species",
                "verbose_name_plural": "Species",
            },
        ),
        migrations.CreateModel(
            name="Staining",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Staining",
                "verbose_name_plural": "Stainings",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
            },
        ),
        migrations.CreateModel(
            name="TileServer",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("public_urls", models.JSONField(default=list)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mymi_data.institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tile Server",
                "verbose_name_plural": "Tile Servers",
            },
        ),
        migrations.CreateModel(
            name="StructureSearch",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                ("is_exam", models.BooleanField(default=False)),
                ("annotation_group_count", models.IntegerField(default=0)),
                ("annotation_count", models.IntegerField(default=0)),
                ("tags", models.JSONField(default=list)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("type", models.CharField(default="structure-search", max_length=20)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mymi_data.image",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mymi_data.institution",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(blank=True, to="mymi_data.subject"),
                ),
            ],
            options={
                "verbose_name": "Structure Search",
                "verbose_name_plural": "Structure Searches",
            },
        ),
        migrations.AddField(
            model_name="image",
            name="organ_systems",
            field=models.ManyToManyField(blank=True, to="mymi_data.organsystem"),
        ),
        migrations.AddField(
            model_name="image",
            name="species",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mymi_data.species",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="staining",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mymi_data.staining",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="tile_server",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mymi_data.tileserver",
            ),
        ),
        migrations.CreateModel(
            name="Exploration",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                ("annotation_group_count", models.IntegerField(default=0)),
                ("annotation_count", models.IntegerField(default=0)),
                ("is_exam", models.BooleanField(default=False)),
                ("edu_id", models.CharField(blank=True, max_length=20)),
                ("tags", models.JSONField(default=list)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("type", models.CharField(default="exploration", max_length=20)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mymi_data.image",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mymi_data.institution",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(blank=True, to="mymi_data.subject"),
                ),
            ],
            options={
                "verbose_name": "Exploration",
                "verbose_name_plural": "Explorations",
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_exam", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("type", models.CharField(default="diagnosis", max_length=20)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mymi_data.image",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mymi_data.institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnosis",
                "verbose_name_plural": "Diagnoses",
            },
        ),
    ]
