# Generated by Django 4.2.7 on 2025-07-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymi_data', '0002_add_annotation_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='scope_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
