# Generated by Django 4.2.7 on 2025-07-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymi_data', '0004_alter_annotationgroup_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='annotation',
            name='external_id',
            field=models.IntegerField(blank=True, help_text='Original ID from MyMi API', null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
