# Generated by Django 4.2.6 on 2025-07-30 15:59

from django.db import migrations, models
import mymi_data.models.structure_search


class Migration(migrations.Migration):
    dependencies = [
        ("mymi_data", "0005_alter_annotation_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuresearch",
            name="solution_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload solution image for this structure search",
                null=True,
                upload_to=mymi_data.models.structure_search.structure_search_solution_upload_path,
            ),
        ),
    ]
